### ISSUE TITLE
Belt tension for sapphire plus 

### ISSUE THREAD

**Issue by DavaD85** [pkucmus/EVA#11]
Hi
My Sapphire plus have the belts in the opposite side and I need to mirror this part, it's possible? 
![20200507_222422](https://user-images.githubusercontent.com/24620134/81343794-ebeed680-90b5-11ea-82b3-f3647164b3da.jpg)
![Uploading 20200507_222611.jpg…]()

**Comment by DavaD85** [comment]
![20200507_222611](https://user-images.githubusercontent.com/24620134/81344007-46883280-90b6-11ea-8989-4d83a7df22c5.jpg)

**Comment by pkucmus** [comment]
Since we started talking about it outside of GitHub it's already done :D 

https://github.com/pkucmus/EVA/blob/flipped_slider/stl/Dynamic%20-%20Slider.stl

Please let me know if it works.

**Comment by DavaD85** [comment]
Hi
As you can see I need to move the belt a little 
![20200508_165239](https://user-images.githubusercontent.com/24620134/81428489-99b4c080-915c-11ea-9ec5-570213718b22.jpg)
And the part is a little lower than the original

**Comment by pkucmus** [comment]
I think we talked about it. Two things can be done here:
1. Thicken the back part to offset the belt tensioner
2. Change the XY joiner part of the printer

I'd rather opt for the later one, since there's already little space in Y on that printer.

**Comment by pkucmus** [comment]
Different belt tension sliders are now available - fill support for Sapphire plus is not something I can take on. Closing this one :)
