### ISSUE TITLE
Requested Mosquito/Nf-Crazy Mount

### ISSUE THREAD

**Issue by morpheus200** [pkucmus/EVA#17]
Request for Mosquito or NF-Crazy (Clone) Hotend. The Hotend is almost compatible with the V6, the differences are very small.

**Comment by pkucmus** [comment]
There are people trying to organize those for me so that I can measure, design and test - so it's coming, but has no ETA yet.

**Comment by joaobarros** [comment]
Plus one on this request, let me know if you need anything

**Comment by pkucmus** [comment]
I should get a Mosquito soon (I hope) I'll start the work then.

**Comment by maziggy** [comment]
+1

**Comment by pkucmus** [comment]
Those are ready to be tested, once I'll do my testing I'll release, you can try to use the current version but stuff may change. Also If you'll use please share your feedback: https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/w/fd185c58d38d06bda7ec83a6/e/180aabbd13bbeefb972e31a1
![mosq](https://user-images.githubusercontent.com/6347418/95836851-36007600-0d40-11eb-8108-65bcd61b8388.gif)

**Comment by EduardoOliveira** [comment]
The fan face looks awesome

**Comment by maziggy** [comment]
> Those are ready to be tested, once I'll do my testing I'll release, you can try to use the current version but stuff may change.

Where can I find it?

**Comment by pkucmus** [comment]
Please check out the unified BMG/BMG-M approach that also gets rid of the groove mount adapter requirement. Thanks miklschmidt!
https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/w/fd185c58d38d06bda7ec83a6/e/db5e779d6e295e18e56f51d3

**Comment by miklschmidt** [comment]
Muuuch better! 👍

**Comment by maziggy** [comment]
When using a BMG-M I don't see any advantage compared to the design before?

**Comment by miklschmidt** [comment]
@maziggy There's no real benefit to the BMG-M version unless the mosquito is mounted directly to the extruder (shorter filament travel path). As far as i can tell, that's not possible in the current EVA design.

**Comment by pkucmus** [comment]
EVA is much about supporting what people may have on hand, if one is switching to EVA from a Mosquito with a BMG that BMG is likely a BMG-M, so we wanted EVA to support either one of those. This particular update makes me happy since in theory one set of those parts can support both permutations. I hope to have it tested soon.

**Comment by maziggy** [comment]
Thanks, makes sense. I already printed the former version and will try it today.

**Comment by maziggy** [comment]
Found a little issue. Printed all parts for a mgn12 carriage and found out that the front plate doesn't fit. The screw holes are to close to each other. It looks like the top_mgn15_bmg.stl fits to a mgn12h. Printing it while writing and let you know.

**Comment by maziggy** [comment]
Just fount out that your model is for a mgn12c. I have a mgn12h. Will move the screw holes.

**Comment by maziggy** [comment]
Will test it now. Assembling was no issue. Very nice design.
![IMG_0052](https://user-images.githubusercontent.com/17797632/97102981-27a04b80-16aa-11eb-9bce-809481467e21.png)

**Comment by pkucmus** [comment]
1.4.0-RC2 carries newest improvements (still work in progress): https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/v/93a8541e17dd938c15833def/e/db5e779d6e295e18e56f51d3

**Comment by maziggy** [comment]
> Those are ready to be tested, once I'll do my testing I'll release, you can try to use the current version but stuff may change. Also If you'll use please share your feedback: https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/w/fd185c58d38d06bda7ec83a6/e/180aabbd13bbeefb972e31a1
> ![mosq](https://user-images.githubusercontent.com/6347418/95836851-36007600-0d40-11eb-8108-65bcd61b8388.gif)

Are you aware of any filament path issues in this version? First print was successfull but after unloading the filament I was not able to load a new one. Filament was stuck at the end of the printed part diretly above the Mosquito. Cleared the path and again the first print was good but problems reoccured when changing filament.

**Comment by miklschmidt** [comment]
@maziggy you should use a piece of bowden tube between the BMG and the Mosquito.

**Comment by pkucmus** [comment]
Added some clearance to the PTFE hole, 1.4.0-RC3: https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/v/630104b77ee640cfa5db0a31/e/1cca3cb2ad6c3a96d3e9486e

**Comment by maziggy** [comment]
Thanks, works perfect.

**Comment by pkucmus** [comment]
Mosquito support is now released in 1.4.0. Thanks for all the input!

**Comment by maziggy** [comment]
Within the last few months I've tried mayn different designs for the combination Mosquito and Bondtech. Some good ones but nothing without any disadvantages. After printing now for two weeks with your design I can say that's the way to go for me. No issues at all.

To tell a long story short: no knick-knack, very easy to assemblle and it just works reliable as it should. Many thanks for your work!!!
