### ISSUE TITLE
Request for alternative belt fixation

### ISSUE THREAD

**Issue by morpheus200** [pkucmus/EVA#20]
Could you provide a "old school" belt fixation with two holes and a zip for the backplate?

**Comment by pkucmus** [comment]
One that would have no built-in tensioning?

**Comment by morpheus200** [comment]
Yes without built-in tensioning, same as the frontplate.

**Comment by pkucmus** [comment]
What we could do here is to make a tension slider that will behave in that manner, to be frank I really don't want to support another variant of the back :)

**Comment by pkucmus** [comment]
Please move this Issue to EVA 2 https://github.com/EVA-3D/eva-main/issues if it's still something to desire :) (please also put the link to this issue there)
