### ISSUE TITLE
Mirrored Bondtech BMG Top Mount

### ISSUE THREAD

**Issue by nexx** [pkucmus/EVA#22]
As requested, I am opening this issue regarding mirroring the BMG top mount.

You may wish to mention in the documentation that the BMG Top can be mirrored to allow for use with the mirrored BMG extruders. I have tested this and can confirm everything lines up as expected.

Thanks for the fantastic work on the EVA design!

**Comment by pkucmus** [comment]
Aaand I forgot to mention that in 1.3.0 :D There's probably some English to fix there so I'll add the info about this in one go.

**Comment by pkucmus** [comment]
Applied to:
https://pkucmus.github.io/EVA/assemblies/v6_titan/ and https://pkucmus.github.io/EVA/assemblies/v6_bmg/
Thanks!
