### ISSUE TITLE
Duet 3 Toolboard Support

### ISSUE THREAD

**Issue by philkry** [pkucmus/EVA#24]
Amazing design you came up with, like it a lot!

For my new CoreXY printer i'm planning to make use of the new Duet 3 Toolboards (https://duet3d.dozuki.com/Wiki/Duet_3_Tool_Board) to reduce the number of cables running to my extruders.

Have you considered supporting it on your EVA platform?

It can be mounted onto a Hemera, so it can be used directly with only minor changes to Z probe mounts.
However for the other extruders, i'm unsure how to integrate it.

**Comment by philkry** [comment]
Hey, i spent some time tweaking the V6 BMG version. It is not ideal yet and requires more tweaking as it sticks out to the side a bit too much.
![IMG_0296](https://user-images.githubusercontent.com/776661/88048007-d8022f00-cb52-11ea-8de6-afee55cd516e.jpg)
![IMG_0516](https://user-images.githubusercontent.com/776661/88048028-e05a6a00-cb52-11ea-81a0-b82ce173453c.jpg)

**Comment by pkucmus** [comment]
Nice. The drawback is that the motor size is limited now but I'm happy that you put work in to EVA. Thanks!

To say that EVA can support the tool board I would need to add that capability to all variants - not sure it's feasible.

**Comment by philkry** [comment]
Yes, i was considering the stepper size as well, but thought when using a geared BMG extruder, you most likely will only require a pancake stepper rather than a full sized one. It would also make the overall assembly considerably more heavier.

I agree, its probably not really feasible to integrate it into all mounts, maybe using a Toolboard is even too niche but i thought i share this as i plan to build my new printer from scratch based on them (but i also only plan to use Hemera and V6 BMG).

I will post updates here in case someone else finds it useful.

**Comment by pkucmus** [comment]
Awesome. Let me know when you are done and would like to be featured in EVA's documentation.

**Comment by philkry** [comment]
so i did some changes to my initial design. i did move the mount to the side of the top module. this now allows all stepper sizes to be used, but more importantly, allows quicker changing the entire carriage. 
with the toolboard mounted at the back (first iteration) you needed to disassemble the entire thing to get the motor out, which kinda defies the purpose of using a toolboard entirely.

you can find my version (mgn15 only for now) here https://github.com/philkry/EVA/blob/master/stl/Tops/top_MGN15_bmg_toolboard.stl

please note, it is still untested as i'm waiting for my printer to be delivered ;)

![IMG_7258](https://user-images.githubusercontent.com/776661/89789787-5da94700-db21-11ea-8ef7-cd1119ad7fff.jpg)

**Comment by philkry** [comment]
@arsi-apli nice design! 
just wondering, is there a reason why you did not just use the Hemera Alternative version of EVA? It would allow to mount the toolboard directly onto the front of Hemera, just the probe mount would need adjustment. that way you could stay as close to 'stock' EVA as possible.
dont get me wrong, it looks good, although more complicated than i think it needs to be.

**Comment by pkucmus** [comment]
There are a few things to consider:
1. What is the benefit of having the tool head? Having it on a fixed Hemera carriage is just reducing the cables required from the main board to the carriage, right? Quite frankly it does not seem compelling. (more in point 3)
2. To be a part of the EVA platform a feature needs to work for all variants, the top part feels like a more proper or generic place to mount this.
3. Let's look into the crystal ball a little bit here: if EVA was to support tool changers, it would be a face with the locking mechanism that would grab a face that would hold a tool board, maybe? I don't know yet.

**Comment by philkry** [comment]
> What is the benefit of having the tool head? Having it on a fixed Hemera carriage is just reducing the cables required from the main board to the carriage, right? Quite frankly it does not seem compelling. (more in point 3)

well, yes. the reduced amount of cables was my initial reason to opt for a toolboard. i like the EVA platform as it would allow me to reduce the efforts needed on manual changing the tool heads. less cables help here as the EVA carriage would be pretty much self-contained and you could just connect power + CAN bus.

on the other hand, you could achieve the same by crimping connectors to all cables (2 fans, thermistor, heater, probe) but that makes it bulky and not so easy to use again. if EVA ever makes it towards a tool changer system (your point 3) that point would even become obsolete as you would have the tools permanently connected. 

were i still see benefits though, even on the long term is, that the tool board also provides you with an additional stepper driver for your extruder. you would not need extension boards anymore and could again achieve self-contained EVA carriages which contain everything you need for driving an extruder assembly. 

> To be a part of the EVA platform a feature needs to work for all variants, the top part feels like a more proper or generic place to mount this.

good point! makes sense.

**Comment by joaobarros** [comment]
I too am interested in this, the toolboards will become more mainstream as they will be supported in the upcoming Duet 3 Mini
High-end heaters and temp sensors come with short cables so board placement and thus distance is important, just wanted to point that what 😉

**Comment by arsi-apli** [comment]
My opinion is that the toolboard helps to reduce vibrations. A common bundle of cables already weighs something, plus the load they exert on the printhead is not linear. That's the main reason I want to use it. And other benefits that have already been mentioned. 

Unfortunately, there are belts by the sides and therefore I'm still thinking about putting the linear rail down and a flat cable for power supply and CAN Bus will be stored in the upper slot in the ALU profile with a short loop to the print head. The same mounting will be on the second axis.

**Comment by pkucmus** [comment]
Thank you all for the valuable info. I like the idea of supporting the tool board (if that was not obvious). 
I think we need to look at two permutations: 
1. for the top free heads (bowden, aero, hemera) - the tool board flat on top which will not work best with the cable mounts coming in 1.3.0
2. for the top motor ones (titan, bmg) - the tool board behind the motor?

Overall this makes me think about extra holes everywhere - as mounting points for anything extra that people may think about, i.e. "EVA Standard Expansion" screw holes. Then a tool board would just need a mounting part that is compatible with the board on "one side" and with the EVA Expansion holes on the other. It may just be the main feature of EVA 1.4.0.

P.S
EVA 1.3.0 is coming this week

**Comment by pkucmus** [comment]
EVA 1.3.0 is now released please check if it changes anything for you. Maybe you could leverage the new back mounting holes somehow (just a hot guess).

**Comment by pkucmus** [comment]
Played around with it a bit and got this as a result:

![eva_duet_tb_out](https://user-images.githubusercontent.com/6347418/91647265-185da280-ea59-11ea-9e44-aaf21f3a4574.gif)

The top heavy ones (BMG and Titan) would have the vertical variant and the top free ones (bowden, Aero, Hemera) would get the horizontal variant.

TODO:

- Horizontal and vertical need a mounting point for a cable holder
- The tops will need to change to take the screw that will firmly hold the bottom part in place
- Vertical ones need another anchor point (not to rock like crazy when moving in Y)

What do you think? 
https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/v/e72f5d6038b183a8b63f5cd0/e/44f6d805bfa7d15742b3ac6f
(check the assembly aero and assembly BMG files, toggle the configuration in top left to change the variants)

**Comment by philkry** [comment]
Wow, amazing. The cover looks really sleek and is perfect spot for your new logo ;) 

I will test this and give feedback as soon as i built up my printer!

**Comment by pkucmus** [comment]
@philkry please consider this a beta test version. At least what is in the TODO needs to be addressed before we call it done :) I'll give it more time in the evening.

**Comment by pkucmus** [comment]
I've added cutouts for the LEDs and other SMD components that are sticking out close to the case wall
![image](https://user-images.githubusercontent.com/6347418/91669244-bc0b8900-eb13-11ea-8470-e71ec56b05d0.png)
But I can't wrap my head around the cable mount or the vertical variant, I'm afraid it's going to wobble like crazy.

**Comment by pkucmus** [comment]
Can someone please confirm how flat the bottom surface of the board is? A picture would be nice. The original STEP has all the THT legs but I'm wondering if there's anything else.

**Comment by philkry** [comment]
took a two quick pictures. can make more if needed. there are only THT legs, the longest ones are the one for the power connector. their length varies between 1.7-2.2mm on my boards.

![IMG_7303](https://user-images.githubusercontent.com/776661/91898568-38c96f00-ec9c-11ea-8c61-f8e6bcea01ee.jpg)
![IMG_7305](https://user-images.githubusercontent.com/776661/91898581-3d8e2300-ec9c-11ea-9a7d-951015711b2e.jpg)

**Comment by pkucmus** [comment]
Ok, I think I'm at a release candidate point. 
For flat top variants:
![image](https://user-images.githubusercontent.com/6347418/92304113-8afbe000-ef7b-11ea-98e9-47b5d314be30.png)
For BMG and Titan we would leverage a bridge over the motor that will hold the ToolBoard case steady
![image](https://user-images.githubusercontent.com/6347418/92304136-a961db80-ef7b-11ea-9681-4c38f0d44673.png)
![image](https://user-images.githubusercontent.com/6347418/92304144-b41c7080-ef7b-11ea-90cf-bf0bb6cbf0bc.png)

https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/v/47bcc210604fef2704e4d8dc/e/e089ef52b1a648887b30ed21

Please let me know what you think

**Comment by joaobarros** [comment]
I love it 👍 
My only concern is traping heat on the back of the board, specially the stepper.
All Duet boards are designed as the bottom side of the boards as the hot side.

**Comment by philkry** [comment]
i like it as well! looks rock solid.
not sure how hot the stepper actually gets? they designed the toolboard to be mounted directly onto a hemera extruder. there  the heat also gets kinda trapped + it gets additional heat from the stepper motor.

@pkucmus i somehow have trouble exporting the back part. not too familiar with onshape, but if i select the back and click export, i do get the part as STL, but the screw holes for the toolboard mount are actually filled/solid.

**Comment by pkucmus** [comment]
@philkry that is desired, you will need to drill or poke those holes after print. Put that in a slicer and it'll make sense:
![image](https://user-images.githubusercontent.com/6347418/92702850-f82fbc80-f351-11ea-9bd1-377f32ac70e8.png)

**Comment by philkry** [comment]
@pkucmus i printed this in the meantime and can confirm it fits perfectly 👍 
![IMG_7624](https://user-images.githubusercontent.com/776661/94940372-b539b280-04d3-11eb-91d9-dc5cd0c830f2.jpg)

**Comment by pkucmus** [comment]
Awesome, although @joaobarros raised an issue that the screws that are under the tool board may short the pins of the board. No bad experiences there? or did you use some short headed screws?

**Comment by philkry** [comment]
no shorts, the board is just working fine. but to be honest i did not pay too much attention to the screws under the board (normal hex screws), maybe i'm just lucky? 
i don't really wanna take it apart again now to verify, getting the cabling nicely done was too much work :D

**Comment by philkry** [comment]
i just disassembled everything and double checked. and yes, i agree, the motor connector is dangerously close to the screw. i think i was just lucky with my particular toolboard. 
maybe you can make the base a few millimeters thicker so there is a bit of a safty distance?

**Comment by pkucmus** [comment]
As a FYI I think I'll move this out of EVA and put it one some "EVA extras" project, I'm trying to keep up with all the permutations and it's a chore. Any ideas for a better name than "EVA extras"?

**Comment by philkry** [comment]
Guess EVA extras would be fine, other options would be 'EVA extensions' or 'EVA contrib' ?

**Comment by EduardoOliveira** [comment]
I can see contrib for parts that are designed by other members and of which
you only have the step file, linking to external sources, and not
garanteing updates

**Comment by pkucmus** [comment]
Someone suggested "EVA Addons" on Discord, I think that represents that those would be best. Toolboard addon is now in a separate document: https://cad.onshape.com/documents/255cffe335d549be4c0d4c52/w/027a43fe00d211ea4230f02e/e/821b45343fc77d009d4ac8c6 (still work in progress) but once I release everything will be described in main EVA docs

**Comment by kuon** [comment]
But how will you "standardize" the addons mouting in the base EVA? 

Should we consider those 5 holes "addon mount"? But what about variant without the top part (like BGM bowden)?

![image](https://user-images.githubusercontent.com/160200/96594201-a4b67400-12ea-11eb-8ba2-ca382a82b17c.png)

**Comment by pkucmus** [comment]
The 3 hole mount would be a standard. 
For the variants that have their tops free there's doing to be an angled tool board base (so the toolboard will be flat on top). 
The "top heavy" ones get the 2 extra holes for the board base to grab by so that the tool board does not wobble like crazy on Y moves.

**Comment by kuon** [comment]
So if we want to design other addons, we can rely on the 3 holes for variants with no top, and 5 holes for those with "heavy" top?

**Comment by pkucmus** [comment]
I want to say "yes" but I will be more comfortable once I figure this one completely, the 3 holes are set in stone I think, the 2 top ones not so sure, and for the ones with clear top there's an opportunity for a screw or two as well
![image](https://user-images.githubusercontent.com/6347418/96622697-924c3280-130a-11eb-8240-54d9e007f1b9.png)

**Comment by kuon** [comment]
The bracket for the BMG has a very thin wall (red line). I think it should be around 0.4-0.5mm for better printability.

![Part](https://user-images.githubusercontent.com/160200/97198465-1c831380-17af-11eb-9bf7-88edcadce2ac.png)

**Comment by joaobarros** [comment]
So I finally printed my Toolboard cover and I've got some issue, the major one being the extra height of a connector:

![IMG_8490](https://user-images.githubusercontent.com/172337/97596229-6a408b80-19fc-11eb-86fe-e1e161326398.jpeg)

Then it's small details that are difficult to print and can eventually break off, as I broke 2 while clearing the holes:
![IMG_8485](https://user-images.githubusercontent.com/172337/97596249-6d3b7c00-19fc-11eb-9068-452eeca5b1ed.jpeg)
![IMG_8489](https://user-images.githubusercontent.com/172337/97596234-6b71b880-19fc-11eb-800f-47742020ce8c.jpeg)

This part here could be a bit wider:
![IMG_8495](https://user-images.githubusercontent.com/172337/97596204-63197d80-19fc-11eb-91eb-5ae706f6bf58.jpeg)
![IMG_8494](https://user-images.githubusercontent.com/172337/97596222-67de3180-19fc-11eb-80a6-7cbf4710c1eb.jpeg)

This piece here could be wider or even not there at all:
![IMG_8491](https://user-images.githubusercontent.com/172337/97596226-69a7f500-19fc-11eb-936f-6fabe2e83d2c.jpeg)

This details here are difficult to print and borderline, any LED that's soldered a bit off will be an issue. Does it makes sense to have them? 
![IMG_8492](https://user-images.githubusercontent.com/172337/97596225-690f5e80-19fc-11eb-80e3-6e7e8f2bf9de.jpeg)
![IMG_8496](https://user-images.githubusercontent.com/172337/97596250-6e6ca900-19fc-11eb-9981-452f32211489.jpeg)

This piece here could be wider or even not be there at all:
![IMG_8488](https://user-images.githubusercontent.com/172337/97596240-6c0a4f00-19fc-11eb-88ee-9be36cdf40d5.jpeg)
![IMG_8486](https://user-images.githubusercontent.com/172337/97596245-6ca2e580-19fc-11eb-820a-c51ef455d44a.jpeg)

I see @philkry has by the photos the same board version as mine v1.0 and the extra height connector and he says everything fits perfectly which I find very strange?!


And a design challenge:
In order to change something attached to a screwed connector we would have to unscrew 5 screws, 1 of the cable holder and 4 for the cover.
What if the cover is not so pretty, so square but has cutouts so one could screw/unscrew without having to unscrew the hole cover?

**Comment by philkry** [comment]
@joaobarros it could be my slicer settings that made it fit better for me as i was working with negative horizontal expansion to compensate for too narrow holes. 

> This details here are difficult to print and borderline, any LED that's soldered a bit off will be an issue. Does it makes sense to have them?
i would say yes. at least the red led is helpful to see if CAN communication between the two boards works fine. it helped me quite a lot when assembling my printer.

>In order to change something attached to a screw connector we would have to unscrew 5 screws, 1 of the cable holder and 4 for the cover.
i agree, this is not ideal currently. it looks very nice but at the cost of practicality. 
i would also favour a version which would expose the terminals, so we could access the screws without disassembling the entire thing.

**Comment by joaobarros** [comment]
@philkry I understand what you're saying about the slicer settings but that doesn't explain the plug I show on the 1st picture, that's some 2mm at least of extra height.
I'd love to see a photo of that side on your print and Toolboard

**Comment by pkucmus** [comment]
@joaobarros I made changes according to your (amazing) feedback, took a different approach with the bridge mount
https://cad.onshape.com/documents/255cffe335d549be4c0d4c52/w/027a43fe00d211ea4230f02e/e/795e637b64bf65caed4dccd1?configuration=default
![toolboard](https://user-images.githubusercontent.com/6347418/97812078-290bde00-1c7f-11eb-9075-c7efe1229346.gif)

**Comment by pkucmus** [comment]
Moving this to EVA 2 :)
