### ISSUE TITLE
MGH 12H carriage

### ISSUE THREAD

**Issue by cjeannerot25** [pkucmus/EVA#28]
your project is for MGN 12C, it's possible to adapte for MGN 12H ?

**Comment by pkucmus** [comment]
It's MGN15C and MGN12C to adapt to an H carriage one would just need to make a wider top part.

**Comment by cjeannerot25** [comment]
even just changing the hole spacing it should be enough.  if you have the step files, I can make the modification in another branch

**Comment by cjeannerot25** [comment]
I use direct drive stl, i can add a top part 😄

**Comment by pkucmus** [comment]
Please move this Issue to EVA 2 https://github.com/EVA-3D/eva-main/issues if it's still something to desire :) (please also put the link to this issue there)
