### ISSUE TITLE
Use in BLV MGN 12

### ISSUE THREAD

**Issue by cjeannerot25** [pkucmus/EVA#32]
I have a problem for use with BLV MGN, the connection part of the belt is reversed, it should be top right, and bottom left, currently on the EVA project it's reversed. I also use MGN12H and it's MGN12C on the EVA project (I redid the part for the BMG direct drive)

**Comment by pkucmus** [comment]
BLV support was never tested, what if you'd mirror the back part? Not sure if the belts will align though

**Comment by cjeannerot25** [comment]
![image](https://user-images.githubusercontent.com/66156910/91654223-584b7680-eaa7-11ea-850e-087db4d2daf0.jpeg)

I confirm belts is aligned ;)

**Comment by cjeannerot25** [comment]
For back it's possible to connected ![image](https://user-images.githubusercontent.com/66156910/91654307-e293da80-eaa7-11ea-8115-76fa05a3e5cf.jpeg)

**Comment by pkucmus** [comment]
Please see: https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/v/0010d118035086ce95d3908d/e/8c43124770d234ffb36295f8 (notice configuration in top left) - far from being done since this only works for the V6 based variants but for BMG testing purposes should be ok

**Comment by cjeannerot25** [comment]
No it's not possible to use in BLV mgn.

**Comment by pkucmus** [comment]
Moved to EVA 2
