### ISSUE TITLE
Dragon hotend support

### ISSUE THREAD

**Issue by pkucmus** [pkucmus/EVA#34]
Seems like it's working out of the box :) At least dimension-wise (thank you Jonh D. for the pictures and testing!).
I'll leave the issue here in case there are more test results -stuff like: making sure nothing melts, is the air flow adequate, etc.

If there's anything to share in the topic please let me know here.

![119116020_10157823001352075_2081627690029420971_o](https://user-images.githubusercontent.com/6347418/93016895-c1ada800-f5c4-11ea-9fc8-44ef76469316.jpg)
![119418720_10157823001212075_6021792919573650790_o](https://user-images.githubusercontent.com/6347418/93016896-c3776b80-f5c4-11ea-8878-ac6bbad7884d.jpg)
![119175198_10157823001167075_2297553713981653754_o](https://user-images.githubusercontent.com/6347418/93016897-c4100200-f5c4-11ea-8b0c-b7d345be52b4.jpg)
![119288138_10157823001072075_6899819216700207803_o](https://user-images.githubusercontent.com/6347418/93016898-c5412f00-f5c4-11ea-92d0-b865b59954a5.jpg)
![119418401_10157823000697075_623331216096867230_o](https://user-images.githubusercontent.com/6347418/93016902-c6725c00-f5c4-11ea-8403-d025c162cd87.jpg)

**Comment by philkry** [comment]
@pkucmus i'm also using the dragon hotend but but my heater has issues keeping up the temperature.
it is stable until the part cooling fan turns on, then it goes down by 10-15° and never recovers. 
i'm wondering if my heater is bad (brand new E3D high precision 30w) or if the fan duct somehow blows onto the heater cartridge? 
did you experience something similar while testing? if not i will try replacing my heater.

**Comment by pkucmus** [comment]
Horns duct is made not to blow directly on the nozzle or the heat block: 
![image](https://user-images.githubusercontent.com/6347418/94992704-191fb200-058c-11eb-81e8-ab22d0f04b4a.png)
that said there is a lot of air being pushed everywhere - will bounce of the bed or the print, etc. 30W seems pretty weak (I'm using 50W ones), I had similar issues on different printers and 40W heaters, a silicone sock does a good job of isolating the cool air as well. 
Before replacing your heater please run PID tuning and maybe PID tuning with the fan 100% PWM on - to teach it how to properly heat itself under those conditions.
I hope this helps.

**Comment by philkry** [comment]
silicon sock is mounted already and the heater is also PID tuned with having part cooling at 100%.
i have a spare 40w heater here, will try this one and see if it improves. my first guess was just the horn duct, since i use the same heater model and part cooling fan on my Hemera extruder with super stable temperatures.

**Comment by pkucmus** [comment]
Done in EVA 2.1.0: https://github.com/EVA-3D/eva-main/issues/5
