### ISSUE TITLE
Idex version fan mount is too fragile

### ISSUE THREAD

**Issue by kuon** [pkucmus/EVA#37]
![IDEX Backs](https://user-images.githubusercontent.com/160200/94991349-d4434d80-0582-11eb-9ce5-66ab5558c700.png)

The highlighted element is quite fragile and should be made thicker.

**Comment by pkucmus** [comment]
I have thicken the "hooks" by 1mm each, for IDEX and Cartesian Backs, please see: https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/w/fd185c58d38d06bda7ec83a6/e/8d4e73fd9c11258ba0412b03

**Comment by kuon** [comment]
Yeah, that should do it.

**Comment by kuon** [comment]
There is another issue with those two hooks, they are separated by 15.2mm, but my fans are 15.25mm. I looked at different fan datasheets, and the tolerance is between 0.25mm and 0.5mm, so I suggest we change this width to 15.5mm instead of 15.2mm.

**Comment by pkucmus** [comment]
Done, please let me know what you think: https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/w/fd185c58d38d06bda7ec83a6/e/8d4e73fd9c11258ba0412b03

**Comment by kuon** [comment]
Yeah, looks good to me.
