### ISSUE TITLE
V6 face front bottom is really thin

### ISSUE THREAD

**Issue by kuon** [pkucmus/EVA#38]
The V6 front has a really thin part at the bottom (selected face), would it be possible to make it a bit thicker?

![V6](https://user-images.githubusercontent.com/160200/94991462-9abf1200-0583-11eb-820f-f7b85a773741.png)

**Comment by pkucmus** [comment]
I reduced the revolve angle on the V6 face - now it does not cut into the thin bottom face, please check: https://cad.onshape.com/documents/1cea28d26150bba34a3d6614/w/fd185c58d38d06bda7ec83a6/e/8c43124770d234ffb36295f8

**Comment by kuon** [comment]
I have not printed it yet, but it is better in the slicer. It looks like it is ok, I'll reopen if it's still too thin after printing.
