### ISSUE TITLE
Request for 2 in 1 / ZSYong mix hotend

### ISSUE THREAD

**Issue by manuelchaves** [pkucmus/EVA#42]
Request for 2 in 1 / ZSYong mix hotends, two color mix plz. TKS
![featured_preview_ZSYOUNG_MIX](https://user-images.githubusercontent.com/8344682/97849068-cba07d00-1cd0-11eb-9617-ca6e678b9e39.jpg)

https://pt.aliexpress.com/item/4000145873157.html
https://pt.aliexpress.com/item/4000293113610.html

**Comment by EduardoOliveira** [comment]
Is that height compatible with the non mixing one?

**Comment by pkucmus** [comment]
Please move this Issue to EVA 2 https://github.com/EVA-3D/eva-main/issues if it's still something to desire :) (please also put the link to this issue there)
