### ISSUE TITLE
Top part only for MGN12C

### ISSUE THREAD

**Issue by alessg1** [pkucmus/EVA#43]
Your top part is only design for MGN12c witch have 15mm x 20mm distance between holes.
You shoud also make version for MGN12H witch have 20mm x 20mm

**Comment by EduardoOliveira** [comment]
Wich top part do you need? I've edited the tops and printed the BMG, I know the bowden top is also ok, not sure about the other one, I can share if you like. Mng12h

**Comment by alessg1** [comment]
I already modify BGM top to be compatible with MGN12H. But now i need to modify bottom one to be compatible with BLV mgn cube endstop

**Comment by pkucmus** [comment]
Please move this Issue to EVA 2 https://github.com/EVA-3D/eva-main/issues if it's still something to desire :) (please also put the link to this issue there)
