### ISSUE TITLE
[EVA 2.0] Anchor points for zip ties

### ISSUE THREAD

**Issue by joaobarros** [pkucmus/EVA#44]
On EVA version 1.x there where anchor points for zip ties on the Back and I added one on the bottom as can be seen on the following picture:
![image0](https://user-images.githubusercontent.com/172337/99521055-d2471980-298b-11eb-8392-bcdf9b479159.jpg)

Of course this is desirable in EVA 2.0 as well so I propose anchor points as marked with red rectangles:
<img width="474" alt="Untitled 2" src="https://user-images.githubusercontent.com/172337/99521064-d5daa080-298b-11eb-88f5-6f2bce5d21c7.png">

<img width="557" alt="Untitled" src="https://user-images.githubusercontent.com/172337/99521073-d83cfa80-298b-11eb-94f9-7bd08dd95842.png">

**Comment by pkucmus** [comment]
Done in EVA 2 - thanks for pushing for it @joaobarros - it's an awesome improvement
