### ISSUE TITLE
Adjust bl touch mount for DIN 912 screw

### ISSUE THREAD

**Issue by kuon** [pkucmus/EVA#45]
![image](https://user-images.githubusercontent.com/160200/100287068-44af8f00-2f74-11eb-83f6-afaecd008905.png)

To be able to mount the bl touch mount with DIN 912 screw, there should be at least 3mm for the head (only 1mm now).

Here is my modified version (I drilled the part afterward, so it's a bit too deep.)

![image](https://user-images.githubusercontent.com/160200/100287334-ba1b5f80-2f74-11eb-817f-f189fb184f7c.png)

**Comment by pkucmus** [comment]
This changed in EVA 2 https://github.com/EVA-3D/eva-main please check it out
