### ISSUE TITLE
Mosquito front question

### ISSUE THREAD

**Issue by maziggy** [pkucmus/EVA#46]
I'm currently assembling the latest Mosquito version and wondering if the small PTFE tube should go also through the front part?

https://github.com/pkucmus/EVA/blob/master/docs/media/stls/mosquito_front.stl

If so, then the hole is too small.

Thanks, Martin

**Comment by miklschmidt** [comment]
Your PTFE tube shouldn't be thicker than 4mm, the hole is 4.2mm, so it should go through without issues. Have you calibrated your flow?

**Comment by pkucmus** [comment]
This changed in EVA 2 https://github.com/EVA-3D/eva-main please check it out
