### ISSUE TITLE
fan problem 

### ISSUE THREAD

**Issue by DavaD85** [pkucmus/EVA#9]
I need to move a little down the back fan because doesn't fit in my Sapphire plus frame.

**Comment by DavaD85** [comment]
![20200507_224653](https://user-images.githubusercontent.com/24620134/81343562-800c6e00-90b5-11ea-9e1c-40e6c2816cad.jpg)

**Comment by pkucmus** [comment]
I made 4 more versions which total up to 5: 
* 30 deg
* 45 deg
* 60 deg (default)
* 80 deg
* 90 deg

And I will upload those tomorrow.

![image](https://user-images.githubusercontent.com/6347418/81459623-46189600-91a1-11ea-8c1f-90e10f43f757.png)
![image](https://user-images.githubusercontent.com/6347418/81459636-52045800-91a1-11ea-8946-f6878e932b3a.png)
![image](https://user-images.githubusercontent.com/6347418/81459651-5b8dc000-91a1-11ea-9fe2-fe6c5bb3109c.png)

**Comment by DavaD85** [comment]
Did you have time to upload these stl?

**Comment by pkucmus** [comment]
5 different angles are now available: https://pkucmus.github.io/EVA/sub_assemblies/core_xy_back/ also for cartesians https://pkucmus.github.io/EVA/sub_assemblies/cartesian_back/.

Please yet me know here if you are happy with them.

**Comment by pkucmus** [comment]
Closing the request as resolved. Let me know if you need anything else.
